apps/first/urls.py
from django.conf.urls import url
from . import views

app_name="routes"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^process$', views.process, name="process")
]

maps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^login/', include('apps.login.urls'), name="auth"),
    url(r'^', include('apps.first.urls'), name="routes"),
    
]

apps/first/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..login.models import User
class TripManager(models.Manager):
    def add(self, data, id):
        # results = {'status':True, 'errors':[]}
        # if not data['start']:
        #     results['errors'].append("Please enter a starting point")
        #     results['status'] = False
        # if not data['end']:
        #     results['errors'].append("Please enter a starting point")
        #     results['status'] = False
        # if results['status']:
        Trip.objects.create(
                name=data['name'],
                origin=data['start'],
                destination=data['end'],
                creator=User.objects.get(id=id)
            )
        return
# Create your models here.
class Trip(models.Model):
    name = models.CharField(max_length=500)
    origin = models.CharField(max_length=500)
    destination = models.CharField(max_length=500)
    creator =models.ForeignKey('login.user')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = TripManager()

apps/first/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
import googlemaps
from datetime import datetime
from .models import Trip
from ..login.models import User
# Create your views here.
gmaps = googlemaps.Client(key="AIzaSyCE5rc8HduPNe5ZN5B6yLPQYMPmZ1jYTcw")
gkey = "AIzaSyCE5rc8HduPNe5ZN5B6yLPQYMPmZ1jYTcw"

def index(request):
    # Trip.objects.all().delete()
    if not 'id' in request.session:
        request.session.id = 0
        return render(request, 'first/index.html')
    else:
        saved_routes = Trip.objects.filter(creator__id=request.session['id'])
        context = {'saved_routes':saved_routes}
        return render(request, 'first/index.html', context)

def process(request):
    if 'route_choice' in request.POST:
        curr_user = User.objects.get(id=request.session['id'])
        print curr_user.mpg
        route = Trip.objects.get(name=request.POST['route_choice'])
        start = route.origin
        end = route.destination
        mpg = int(curr_user.mpg)
        cost =int(curr_user.cost)
    else:
        start = request.POST['start']
        end = request.POST['end']
        mpg = int(request.POST['mpg'])
        cost = int(request.POST['cost'])

    request.session['start'] = start
    print request.session['start']
    request.session['end'] = end
    request.session['mpg'] = mpg
    request.session['cost'] = cost
    direction_results = gmaps.directions(start,end, mode="driving", departure_time="now", avoid="tolls")
    toll_direction_results = gmaps.directions(start,end, mode="driving", departure_time="now")
    summary =  direction_results[0]['summary']
    distance = direction_results[0]['legs'][0]['distance']['text']
    duration =  direction_results[0]['legs'][0]['duration_in_traffic']['text']
    tsummary =  toll_direction_results[0]['summary']
    tdistance = toll_direction_results[0]['legs'][0]['distance']['text']
    tduration =  toll_direction_results[0]['legs'][0]['duration_in_traffic']['text']
    distance_diff = round(((direction_results[0]['legs'][0]['distance']['value'] - toll_direction_results[0]['legs'][0]['distance']['value'])/1609.34),2)
    time_diff = (direction_results[0]['legs'][0]['duration_in_traffic']['value']-toll_direction_results[0]['legs'][0]['duration_in_traffic']['value'])/60
    gas_saving = round((distance_diff/mpg * 3),2)
    toll = get_toll()
    net_cost = (toll - gas_saving)
    min_per = cost/5
    actual_per = round(time_diff/net_cost, 2)
    status = "should"
    if actual_per < min_per:
        status = "should not"
    # print direction_results
    # print toll_direction_results
    toll_routes = []
    for item in toll_direction_results[0]['legs'][0]['steps']:
        if "toll" in item['html_instructions']:
            print item['html_instructions']
            print item['start_location']
            toll_lat = item['start_location']['lat']
            toll_lng = item['start_location']['lng']
            reverse = gmaps.reverse_geocode((toll_lat,toll_lng))
            toll_routes.append(reverse[0]['address_components'][0]['long_name'])
            print toll_routes, "routes"
    context = {'summary':summary,
            'distance':distance,
            'duration':duration,
            'tsummary':tsummary,
            'tdistance':tdistance,
            'tduration':tduration,
            'time_diff': time_diff,
            'distance_diff': distance_diff,
            'start':start,
            'end': end,
            'toll_routes':toll_routes,
            'gas_saving':gas_saving,
            'toll':toll,
            'net_cost':net_cost,
            'status':status,
            'min_per':min_per,
            'actual_per':actual_per,
            'gkey': gkey
            }
    # print toll_direction_results[0]['legs'][0]['steps']
    if 'save_route' in request.POST:
        print "is checked"
        Trip.objects.add(request.POST, request.session['id'])
    return render(request, 'first/results.html', context)

def get_toll():
    now = datetime.now()
    print now.hour, "nour"
    if now.hour < 5:
        return 1.25
    if now.hour < 6:
        return 2.00
    if now.hour < 7:
        return 3.40
    if now.hour < 9:
        return 4.30
    if now.hour < 10:
        return 3.40
    if now.hour < 14:
        return 2.70
    if now.hour < 15:
        return 3.40
    if now.hour < 18:
        return 4.30
    if now.hour < 19:
        return 3.40
    if now.hour < 21:
        return 2.00
    if now.hour < 23:
        return 2.00
    else:
        return 1.25     

apps/first/templates/first/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Toll Calculations</title>
             {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type = "text/css" href="{% static 'first/css/style.css' %}"> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
    <div class="container-fluid">
    <header>
        <h1>Toll Route Calculator</h1>
    </header>
    <form id="saved_routes" action="process" method="post">
         {% csrf_token %}
    <div class="form-group">
        {% if saved_routes %}
    <label>Saved Routes:</label>
        <select name="route_choice">
            {% for route in saved_routes %}
            <option value="{{route.name}}">{{route.name}}</option>
            {% endfor %}
        </select>
    </div>
        <input type="submit" value="Calculate Route">
    </form>
    {% endif %}
    {% if not saved_routes %}
    <a href="/login/">Log in to save routes</a>
    {% endif %}
    <br>
    <br>
    <form id="routeForm" action="process" method="post">
         {% csrf_token %}
        <div class="form-group">
            <label>Starting location:</label>
            <input class="form-control" type="text" name="start" value="{{request.session.start}}">
        </div>
        <div class="form-group">
            <label>Ending location:</label>
            <input class="form-control" type="text" name="end" value="{{request.session.end}}"><br>
        </div>
        <div class="form-group">
            <label>Enter the gas mileage of your car:</label>
            <input class="form-control" type="text" name="mpg" value={{request.session.mpg}}><br>
        </div>
        <div class="form-group">
            <label>How many minutes would you need to save to pay $5:</label>
            <input class="form-control" type="text" name="cost" value={{request.session.cost}}><br>
        </div>
        <div class="checkbox">
            <label>
            <input type="checkbox" name="save_route">Save Route?
            </label>
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="name" value="Route Name"><br>
        </div>
        <input class="form-control" type="submit" value="Calculate Routes">
    </form>
    </div>
</body>

apps/first/templates/first/results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Results</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'first/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <header>
                <h1><strong>Toll Route Calculator</strong></h1>
                <a href="{% url 'routes:index' %}">Back to routes</a>
            </header>
        </div>
        <div class="row">
            <div class="col-sm-1">
            </div>
            <div class="col-sm-11">
                <h1>Traveling from {{start}} to {{end}}:</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-5">
                <div class="row">
                    <h2><strong>Summary:</strong> You <strong>{{status}}</strong> take the toll route</h2>
                </div>
                <div class="row">
                    <h5>Toll Cost: ${{toll}}</h5>
                    <h5>Time savings: {{time_diff}}</h5>
                    <h5>Distance Savings: {{distance_diff}} miles</h5>
                    <h5>Gas Savings: {{gas_saving}} gallons</h5>
                    <h5>Net Cost: ${{net_cost}}</h5>
                    <h5>Minutes saved per $1: {{actual_per}}</h5>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-4 result">
                <h2><strong> With Tolls:</strong></h2>
                <h3>Taking {{tsummary}} it will take {{tduration}} traveling {{tdistance}}</h3>
                <iframe width="450" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/directions?key=AIzaSyCE5rc8HduPNe5ZN5B6yLPQYMPmZ1jYTcw
                &origin={{start}}&destination={{end}}" allowfullscreen>
                </iframe>
            </div>
            <div class="col-sm-1"></div>
            <div class="col-sm-4 result">
                <h2><strong>Without Tolls</strong></h2>
                <h3>Taking {{summary}} it will take {{duration}} traveling {{distance}}</h3>
                <iframe width="450" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/directions?key=AIzaSyCE5rc8HduPNe5ZN5B6yLPQYMPmZ1jYTcw
            &origin={{start}}&destination={{end}}&avoid=tolls" allowfullscreen>
                </iframe>
            </div>
            <div class="col-sm-1"></div>
        </div>
        <br><a href="{% url 'routes:index' %}">Back</a>
    </div>
</body>