apps/login/urls.py
from django.conf.urls import url
from . import views

app_name = "auth"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login$', views.login, name="login"),
    url(r'^register$', views.register, name="register"),
    url(r'^logout$', views.logout, name="logout")
]

maps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^login/', include('apps.login.urls'), name="auth"),
    url(r'^', include('apps.first.urls'), name="routes"),
    
]

apps/login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import re
import datetime
import bcrypt
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
NAME_REGEX = re.compile('^[a-zA-Z]+$')



class UserManager(models.Manager):
    def register(self, data):
        results = {'status':True, 'errors':[], 'user':None}
        print "model register"
        # print data['first']
        # month, day, year = map(int, data['birth'].split('/'))
        # print datetime.date.today()
        # print datetime.date(year, month, day)
        # if not data['first'] or len(data['first']) < 3:
        #     results['errors'].append('First ame must be at least 3 characters')
        #     results['status']= False
        if not EMAIL_REGEX.match(data['email']):
            results['errors'].append('Email not in valid format')
            results['status'] = False
        if not NAME_REGEX.match(data['first']):
            results['errors'].append('First name must be letters only')
            results['status'] = False
        # if not NAME_REGEX.match(data['last']):
        #     results['errors'].append('Last name must be letters only')
        #     results['status'] = False
        # if datetime.date(year, month, day) >= datetime.date.today():
        #     errors.append('Birth date must be in the past')
        #     pass
        if data['password'] != data['confirm']:
            results['errors'].append('Passwords do not match')
            results['status'] = False
        if len(data['password']) < 8:
            results['errors'].append('Password must be at least 8 characters')
            results['status'] = False
        if User.objects.filter(email=data['email']).exists():
            results['errors'].append('This email is already in use, please choose another')
            results['status'] = False
        if results['status']:
            password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            print "successful register"
            user = User.objects.create(
                first_name=data['first'],
                last_name=data['last'],
                email=data['email'],
                mpg=data['mpg'],
                cost=data['cost'],
                password=password)
            results['user'] = user
            print results
        return results


    def login(self, data):
        results = {'status': True, 'errors':[], 'user': None}
        if not User.objects.filter(email=data['email']).exists():
            results['errors'].append('Email or Password is not correct')
            results['status'] = False
        else:
            user = User.objects.get(email=data['email'])
            passhash = bcrypt.hashpw(data['password'].encode(), user.password.encode())
            if not passhash == user.password.encode():
                print "bad password"
                results['errors'].append('Email or Password is not correct')
                results['status']= False
            else:
                results['user'] = user
                print user
        return results

    def update(self, data):
        user = User.objects.get(id=data['id'])
        user.email = data['email']
        user.first_name = data['first']
        user.last_name = data['last']
        user.save()
        return user

class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email =  models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    mpg = models.SmallIntegerField()
    cost = models.SmallIntegerField()
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at =models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
import datetime


def index(request):
    # User.objects.all().delete()
    return render(request, 'login/index.html')

def login(request):
    print "in login view"
    user= User.objects.login(request.POST)
    if user['status']:
        print "in login view success"
        request.session['name'] = user['user'].first_name
        request.session['id'] = user['user'].id
        request.session['mpg'] = user['user'].mpg
        request.session['cost'] = user['user'].cost
        #Insert starting page in redirect below
        return redirect ('routes:index')
    else:
        print "login view returned errors"
        for error in user['errors']:
            messages.error(request, error, extra_tags="login")
        return redirect('auth:index')

def register(request):
    print "in register"
    user = User.objects.register(request.POST)
    print user
    if not user['status']:
        for error in user['errors']:
            messages.error(request, error, extra_tags="register")
        return redirect ('auth:index')
    else:
        print "register success"
        request.session['name'] = user['user'].first_name
        request.session['id'] = user['user'].id
        request.session['mpg'] = user['user'].mpg
        request.session['cost'] = user['user'].cost
        print request.session['name']
        #Insert starting page in redirect below
        return redirect ('routes:index')    

def logout(request):
    request.session.pop('name')
    return redirect('auth:index')

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Welcome</title>
          {% load staticfiles %}
        <link rel="stylesheet" type = "text/css" href="{% static 'login/css/style.css' %}"> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    </head>
    <body>
        <header>
            <h1>Welcome!</h1>
        </header>
        <form id="login" action="{% url 'auth:login' %}" method='POST'>
            <h2>Login:</h2>
            {% if messages %}
                {% for message in messages %}
                    {% if "login" in message.tags %}
                        <p>{{message}}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% csrf_token %}
            <div class="form-group">
                <label>Email:</label>
                <input class="form-control" type = "text" name="email">
            </div>
            <div class="form-group">
                <label>Password:</label>
                <input class="form-control" type="password" name="password">
            </div>
            <input class="form-control" type="submit" value="Login"> 
        </form>
        <form id="register" action="{% url 'auth:register' %}" method='POST'>
            <h2>Register:</h2>
            {% if messages %}
                {% for message in messages %}
                    {% if "register" in message.tags %}
                        <p>{{message}}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% csrf_token %}
            <div class="form-group">
                <label>First Name:</label>
                <input class="form-control" type="text" name="first">
            </div>
            <div class="form-group">
                <label>Name:</label>
                <input class="form-control" type = "text" name="last">
            </div>
            <div class="form-group">
                <label>Email:</label>
                <input class="form-control" type = "text" name="email">
            </div>
            <div class="form-group">
                <label>MPG of your car:</label>
                <input class="form-control" type="text" name="mpg">
            </div>
            <div class="form-group">
                <label>How much time would you need to save to pay $5?</label>
                <input class="form-control" type="text" name="cost">
            </div>
            <div class="form-group">
                <label>Password:</label>
                <input class="form-control" type="password" name="password">
            </div>
            <div class="form-group">
                <label>Confirm Password:</label>
                <input class="form-control" type="password" name="confirm">
            </div>
            <input class="from-control" type="submit" value="Register"> 
        </form>
    </body>
    </body>
</html>

apps/login/templates/login/success.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login and Registration</title>
          {% load staticfiles %}
        <link rel="stylesheet" type = "text/css" href="{% static '*****/css/main.css' %}"> 
    </head>
    <body>
        <h1>Success! Welcome, {{request.session.first}}!</h1>
        <h2>Successfully {{request.session.status}}!</h2>
    </body>